### ISSUE TITLE
User can not upload a dataset and the error is no good

### ISSUE THREAD

**Issue by wbazant** [VEuPathDB/service-user-dataset-import#3]
<img width="1424" alt="Screenshot 2020-06-26 23 36 46" src="https://user-images.githubusercontent.com/16976512/86018588-8fdc6a80-b9f3-11ea-8a78-741115355a00.png">

"parameter 9 missing" sounds like bad sql

**Comment by Foxcapades** [comment]
Seems like the service isn't running the most recent version.

**Comment by Foxcapades** [comment]
Request ID: `55firGffJ7taHMDK0ZIpX1`
Stacktrace:
```
2020-06-29 14:18:45.807 [ERROR][55firGffJ7taHMDK0ZIpX1]: failed to create new job entry
org.postgresql.util.PSQLException: No value specified for parameter 9.
        at org.postgresql.core.v3.SimpleParameterList.checkAllParametersSet(SimpleParameterList.java:270) ~[service.jar:1.0.3]
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:297) ~[service.jar:1.0.3]
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448) ~[service.jar:1.0.3]
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369) ~[service.jar:1.0.3]
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:159) ~[service.jar:1.0.3]
        at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:148) ~[service.jar:1.0.3]
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44) ~[service.jar:1.0.3]
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java) ~[service.jar:1.0.3]
        at org.veupathdb.service.userds.repo.InsertJobQuery.run(InsertJobQuery.java:20) ~[service.jar:1.0.3]
        at org.veupathdb.service.userds.service.JobService.insertJob(JobService.java:61) ~[service.jar:1.0.3]
        at org.veupathdb.service.userds.controller.UserDatasetController.createJob(UserDatasetController.java:116) ~[service.jar:1.0.3]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[service.jar:1.0.3]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124) [service.jar:1.0.3]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167) [service.jar:1.0.3]
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176) [service.jar:1.0.3]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79) [service.jar:1.0.3]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469) [service.jar:1.0.3]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391) [service.jar:1.0.3]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80) [service.jar:1.0.3]
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253) [service.jar:1.0.3]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) [service.jar:1.0.3]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) [service.jar:1.0.3]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292) [service.jar:1.0.3]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274) [service.jar:1.0.3]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:244) [service.jar:1.0.3]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) [service.jar:1.0.3]
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232) [service.jar:1.0.3]
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680) [service.jar:1.0.3]
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:356) [service.jar:1.0.3]
        at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:200) [service.jar:1.0.3]
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569) [service.jar:1.0.3]
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549) [service.jar:1.0.3]
        at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by Foxcapades** [comment]
File: `src/main/java/org/veupathdb/service/userds/repo/InsertJobQuery.java`
Cause:
* Parameter is missing, the insert is not setting the dataset type.

**Comment by Foxcapades** [comment]
This should be available in the next few hours.  Jenkins is triggered once per hour on this repo and there may be some delay between jenkins rebuilding and the image actually being deployed.
